version: '3'
services:
  node_exporter:
    image: vuongtlt13/node_exporter
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    ports:
      - ${NODE_EXPORTER_PORT}:9100  # Порт для доступа к Node Exporter
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    environment:
      - BASIC_AUTH_USERNAME=$USER # Имя пользователя
      - BASIC_AUTH_PASSWORD=$PASSWORD # Пароль

  cadvisor:
    image: vuongtlt13/cadvisor
    container_name: cadvisor
    ports:
      - ${CADVISOR_PORT}:8080 # Порт для доступа к Cadvisor
    command: 
     - "--housekeeping_interval=5s"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    environment:
      - BASIC_AUTH_USERNAME=$USER
      - BASIC_AUTH_PASSWORD=$PASSWORD
    privileged: true