version: '3.7'

networks:
  monitor-net:

services:
  prometheus:
    image: prom/prometheus:v2.36.2
    user: ${USER_GID_UID} # UID и GID для запуска контейнера
    volumes:
      - ${PROMETHEUS_CONFIG_DIR}:/etc/prometheus/ # Директория конфигурации Prometheus
      - ${PROMETHEUS_DATA_DIR}:/prometheus # Директория данных Prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - ${PROMETHEUS_PORT}:9090 # Порт для Prometheus
    depends_on:
      - cadvisor
    networks:
      - monitor-net
    restart: on-failure

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - monitor-net
    restart: on-failure

  alertmanager:
    image: prom/alertmanager
    user: ${USER_GID_UID} # UID и GID для запуска контейнера
    volumes:
      - ${ALERTMANAGER_CONFIG_DIR}:/etc/alertmanager # Директория конфигурации Alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - ${ALERTMANAGER_PORT}:9093 # Порт для Alertmanager
    networks:
      - monitor-net
    restart: on-failure

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitor-net
    restart: on-failure

  grafana:
    image: grafana/grafana
    user: ${USER_GID_UID} # UID и GID для запуска контейнера
    depends_on:
      - prometheus
    volumes:
      - ${GRAFANA_DATA_DIR}:/var/lib/grafana # Директория данных Grafana
      - ${GRAFANA_PROVISIONING_DIR}:/etc/grafana/provisioning/ # Директория provisioning Grafana
    ports:
      - ${GRAFANA_PORT}:3000 # Порт для Grafana
    networks:
      - monitor-net
    restart: on-failure
