version: "3.2"
services:
  plex:
    image: linuxserver/plex:version-1.30.1.6562-915986d62
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /docker/plex:/config
      - type: volume
        source: MyBOX
        target: /MyBOX
        volume:
          nocopy: true
    healthcheck:
      test: ["CMD-SHELL", "df -hT | grep nfs || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      
volumes:
  MyBOX:
    driver_opts:
      type: "nfs"
      o: "addr=172.16.0.15,nolock,soft,rw"
      device: ":/mnt/user/MyBOX"
