version: "3"

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - ${WG_VOLUME}:/config
    ports:
      - ${UI_PORT}:5000 # Порт по которому будет доступен веб-интерфейс
      - ${WG_PORT}:${WG_PORT_INTERNAL}/udp # Порты для доступа к WireGuard

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
#      - SENDGRID_API_KEY
#      - EMAIL_FROM_ADDRESS
#      - EMAIL_FROM_NAME
#      - SESSION_SECRET
      - WGUI_USERNAME=$USER # Имя пользователя для UI
      - WGUI_PASSWORD=$PASSWORD # Пароль для UI
#      - WG_CONF_TEMPLATE
#      - WGUI_MANAGE_START=true
#      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ${UI_VOLUME}:/app/db
      - ${WG_VOLUME}:/etc/wireguard