---
- name: Install the ALD Pro client package
  ansible.builtin.apt:
    update_cache: true
    name: "{{ _aldpro_client_pkgs }}"
    state: present

- name: Set server hostname to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ aldpro_pdc_ip }} {{ aldpro_pdc_name }}.{{ aldpro_domain }} {{ aldpro_pdc_name }}"
    state: present

- name: Add ALD Pro dc in resolv.conf
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      domain {{ aldpro_domain }}
      nameserver {{ aldpro_pdc_ip }}

- name: Collect services facts
  ansible.builtin.service_facts:

- name: Run ALD Pro client installer script
  ansible.builtin.shell: >
    {{ _aldpro_client_installer }}
    -c {{ aldpro_domain }}
    -u admin
    -p '{{ aldpro_admin_password }}'
    -d {{ inventory_hostname }}
    -i
    -f
