---
- name: Install ALD Pro server packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{_aldpro_controller_pkgs}}"
    state: present

- name: Enable password authentification
  ansible.builtin.lineinfile:
    path: /etc/apache2/conf-aldpro/aldpro-mp.conf
    line: '  GssapiBasicAuth On'
    insertafter: '<Location "/ad">'

- name: Set correct DNS
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: "nameserver 127.0.0.1"

- name: Run ALD Pro install script
  ansible.builtin.shell: >
    /usr/bin/bash {{ _aldpro_freeipa_install_script }}
    -d {{ aldpro_domain }}
    -n {{ inventory_hostname }}
    -p '{{ aldpro_admin_password }}'
    --ip {{ ansible_host }}
    --no-reboot

- name: Set global DNS forward zone
  block:
    - name: Format input for ipadnsconfig module
      ansible.builtin.set_fact:
        ipa_forwarders: "{{ ipa_forwarders | default([]) + [{'ip_address': item}] }}"
      loop: "{{ aldpro_global_forwarders }}"

    - name: Set up DNS forwarders
      register: forwarders_result
      freeipa.ansible_freeipa.ipadnsconfig:
        ipaadmin_password: "{{ aldpro_admin_password }}"
        forwarders: "{{ ipa_forwarders }}"
        state: present
  rescue:
    - ansible.builtin.debug:
        msg: "{{ forwarders_result }}"

    - name: Restart Kerberos 5 Key Distribution Center
      ansible.builtin.systemd:
        name: krb5-kdc.service
        state: restarted
        daemon_reload: true

    - name: Re-run setting up DNS forwarders
      freeipa.ansible_freeipa.ipadnsconfig:
        ipaadmin_password: "{{ aldpro_admin_password }}"
        forwarders: "{{ ipa_forwarders }}"
        state: present
      ignore_errors: true

- name: Allow DNS recursion for any networks
  ansible.builtin.lineinfile:
    path: /etc/bind/ipa-options-ext.conf
    line: "allow-recursion { any; };"
    state: present
  register: dns_recursion_policy

- name: Restart BIND Domain Name Server with native PKCS#11
  ansible.builtin.systemd:
    name: bind9-pkcs11.service
    state: restarted
    daemon_reload: true
  when: dns_recursion_policy is changed
