---
################# ALD PRO general variables ############################
# ALD Pro domain name
aldpro_domain: "{{ _undef }}"

# ALD Pro admin password
aldpro_admin_password: "{{ _undef }}"

# ALD Pro version
aldpro_version: "1.4.1"

# ALD Pro extended repository version
aldpro_extended_version: "generic"

# ALD Pro deb repo
aldpro_repo:
  - deb https://artifactory.astralinux.ru/artifactory/aldpro-main {{ aldpro_version }} main
  - deb https://artifactory.astralinux.ru/artifactory/aldpro-extended {{ aldpro_extended_version }} main

# ALD Pro deb repo state
# Values: present | absent
aldpro_repo_state: "present"

################# ALD PRO controller variables ##########################
aldpro_global_forwarders:
  - 8.8.8.8
  - 8.8.4.4
aldpro_server_minimal_memory_mb: 4096

################# ALD PRO client variables ##############################
# ALD Pro server ip
aldpro_pdc_ip: "{{ _undef }}"

# ALD Pro server name. It will be set at the hostname for domain controller (for clients only)
aldpro_pdc_name: "{{ _undef }}"
