---
- name: Collect facts
  ansible.builtin.setup:

# Get Astra version
- name: Get Astra Linux version
  ansible.builtin.command: 'cat /etc/astra/build_version'
  register: _astra_version_result
  changed_when: false
  failed_when: false

# This task will not stop playing, but will tell us which host fails.
- ansible.builtin.fail:
    msg: "Expected Astra Linux distribution but discovered by {{ ansible_distribution }}."
  when: _astra_version_result.rc != 0

# Show an error message and stop playing if at least one host does not have an astra_version file.
- ansible.builtin.fail:
    msg: "At least one host has an unsupported distribution. See above."
  run_once: true
  when: 1 in ansible_play_hosts_all | map('extract', hostvars, '_astra_version_result') | list | map(attribute='rc')

# Extract Astra version to global variable
- name: Set value for the astra_version variable
  ansible.builtin.set_fact:
    _astra_version: '{{ (_astra_version_result.stdout | trim | regex_search("\D?((\d+\.)+\d+).*", "\1"))[0] }}'
