---
- name: Set hostname
  ansible.builtin.hostname:
    use: systemd
    name: "{{ inventory_hostname }}.{{ aldpro_domain }}"

- name: Add host record to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_host }} {{ inventory_hostname }}.{{ aldpro_domain }} {{ inventory_hostname }}"
    state: present
