---
- name: Collect and set facts
  ansible.builtin.include_tasks: collect_facts.yml

- name: Check general conditions and vars
  ansible.builtin.include_tasks: precondition_general.yml

- name: Check ald pro controller conditions and vars
  ansible.builtin.include_tasks: precondition_controller.yml
  when: "'astra.ald_pro.controller' in ansible_play_role_names"

- name: Check ald pro client conditions and vars
  ansible.builtin.include_tasks: precondition_client.yml
  when: "'astra.ald_pro.client' in ansible_play_role_names"

- name: Set hostname information
  ansible.builtin.include_tasks: hostname.yml

- name: Manage ald pro repository
  ansible.builtin.include_tasks: repository.yml
