---
- name: Check if the role is not played directly
  ansible.builtin.fail:
    msg: "The role {{ ansible_role_name }} not to be played directly."
  when:
    - ansible_role_name in ansible_play_role_names
  run_once: true

- name: Check general required variables
  ansible.builtin.assert:
    fail_msg: "Not all general required variables are defined"
    that:
      - aldpro_domain
      - aldpro_admin_password
  run_once: true

- name: Check for Astra Linux version support
  ansible.builtin.assert:
    fail_msg: "Unsupported version of Astra Linux {{ _astra_version }}"
    quiet: true
    that: (_astra_version is version('1.7', '>=') and _astra_version is version('1.8', '<'))
