---
version: '3'

tasks:
  test:
    deps: [update:box, install:requirements]
    dir: tests
    env:
      HOME: /root/
      VAGRANT_DISTRO: alse-smolensk
    cmds:
      - echo "Run test on alse-1.7 mode 'Smolensk'"
      - task: test:alse-smolensk

  destroy:
    env:
      HOME: /root/
      VAGRANT_DISTRO: '{{default "alse-smolensk" .VAGRANT_DISTRO}}'
    dir: tests
    cmds:
      - vagrant destroy -f

  clean:
    env:
      HOME: /root/
    dir: tests
    cmds:
      - rm -rf collections || true
      - rm -rf .vagrant || true

  update:box:
    env:
      HOME: /root/
    dir: tests
    cmds:
      - vagrant box update
      - vagrant box prune

  test:alse-smolensk:
    dir: tests
    vars:
      VAGRANT_DISTRO: alse-smolensk
    env:
      HOME: /root/
      VAGRANT_DISTRO: "{{.VAGRANT_DISTRO}}"
    cmds:
      - vagrant up
      - task: install:requirements
      - task: run:aldpro
      - task: destroy
        vars: {VAGRANT_DISTRO: "{{.VAGRANT_DISTRO}}"}
      - task: clean

  install:requirements:
    dir: tests
    cmds:
      - ansible-galaxy install -r requirements.yml

  run:aldpro:
    internal: true
    cmds:
      - >
        docker run -t --rm
        -v $(getent passwd `whoami`| awk -F ":" '{print $6}')/.ssh/id_rsa:/root/.ssh/id_rsa_ro:ro
        -v `pwd`:/opt/play
        -w /opt/play/tests
        registry.astralinux.ru/library/aa-base-ee:0.1.1 \
          sh -c "
            cp -f ~/.ssh/id_rsa_ro ~/.ssh/id_rsa;
            chmod 600 ~/.ssh/id_rsa;
            ansible-playbook test.yml
          "
