---
- hosts: server
  become: yes
  tasks:
    - name: Ensure cloud-init does not update /etc/hosts
      lineinfile:
        path: /etc/cloud/cloud.cfg
        backrefs: yes
        regexp: '^\s*- update_etc_hosts'
        state: absent
    - name: Ensure cloud-init does not update /etc/hostname
      lineinfile:
        path: /etc/cloud/cloud.cfg
        backrefs: yes
        regexp: '^\s*- update_hostname'
        state: absent
  handlers:
    - name: Restart cloud-init
      systemd:
        name: cloud-init
        state: restarted