---
- name: Executing script of deleting server k3s
  hosts: masters
  become: yes
  tasks:

    - shell: /usr/local/bin/k3s-uninstall.sh
    
- name: Executing script of deleting agent k3s
  hosts: agents
  become: yes
  tasks:

    - shell: /usr/local/bin/k3s-agent-uninstall.sh